const yearEl=document.getElementById('year');if(yearEl)yearEl.textContent=new Date().getFullYear();
const header=document.getElementById('site-header'),sideNav=document.getElementById('side-nav'),sideProgress=document.getElementById('side-progress'),toggle=document.querySelector('.nav-toggle'),nav=document.getElementById('site-nav'),prefersReduced=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches,body=document.body;
const openNav=()=>{if(!nav)return;nav.classList.add('open');if(toggle)toggle.setAttribute('aria-expanded','true');body.style.overflow='hidden'};
const closeNav=()=>{if(!nav)return;nav.classList.remove('open');if(toggle)toggle.setAttribute('aria-expanded','false');body.style.overflow=''};
if(toggle&&nav){toggle.addEventListener('click',()=>{const o=nav.classList.contains('open');o?closeNav():openNav()});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeNav()));document.addEventListener('click',e=>{if(!nav.classList.contains('open'))return;const inside=nav.contains(e.target)||toggle.contains(e.target);if(!inside)closeNav()},{passive:true});document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!nav.classList.contains('open'))return;const f=nav.querySelectorAll('a,button');if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})}
;(function(){const c=document.getElementById('matrix');if(!c||prefersReduced)return;const x=c.getContext('2d',{alpha:true}),chars='01𝛌𝛑∑ΛПЖ¥#/*+-<>[]{}≈≡⇢⇠⟐⟡αβγδεζηθικλμνξοπρστυφχψω'.split(''),color='#30f179',trail=.08;let w,h,cols,drops,fs,dpr;function resize(){dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));w=Math.floor(innerWidth);h=Math.floor(innerHeight);c.width=Math.floor(w*dpr);c.height=Math.floor(h*dpr);c.style.width=w+'px';c.style.height=h+'px';x.setTransform(dpr,0,0,dpr,0,0);fs=Math.max(13,Math.min(20,Math.floor(w/95)));cols=Math.floor(w/fs);drops=new Array(cols).fill(0).map(()=>Math.floor(Math.random()*h));x.font=`${fs}px "JetBrains Mono", ui-monospace, monospace`}let last=0;function draw(ts){requestAnimationFrame(draw);if(ts-last<16)return;last=ts;x.fillStyle=`rgba(3,7,5,${trail})`;x.fillRect(0,0,w,h);x.shadowColor=color;x.shadowBlur=8;x.fillStyle=color;for(let i=0;i<drops.length;i++){const t=chars[(Math.random()*chars.length)|0],X=i*fs,Y=drops[i]*fs;x.fillText(t,X,Y);if(Y>h&&Math.random()>.975)drops[i]=0;else drops[i]++}}resize();addEventListener('resize',resize,{passive:true});requestAnimationFrame(draw)})();
let lastY=window.scrollY;function onScroll(){const y=window.scrollY,down=y>lastY;lastY=y;if(header){if(y>80&&down)header.classList.add('header-hidden');else header.classList.remove('header-hidden')}if(sideNav){if(y>140)sideNav.classList.add('visible');else sideNav.classList.remove('visible')}if(sideProgress){const docH=document.documentElement.scrollHeight-window.innerHeight,p=Math.max(0,Math.min(1,y/(docH||1)));sideProgress.style.height=`${Math.round(p*100)}%`}}addEventListener('scroll',onScroll,{passive:true});addEventListener('load',onScroll);
function targetFor(el){const r=el.getBoundingClientRect(),vh=innerHeight,h=Math.min(r.height,vh),center=r.top+scrollY-(vh-h)/2,offset=window.matchMedia('(max-width: 860px)').matches?100:140,top=r.height<vh*0.92?center:r.top+scrollY-offset;return Math.max(0,top)}
function smoothTo(id){const el=document.getElementById(id)||document.querySelector(`[id="${id}-section"]`);if(!el)return;scrollTo({top:targetFor(el),behavior:'smooth'})}
document.querySelectorAll('.site-nav a[href^="#"], .side-nav a[href^="#"]').forEach(a=>{a.addEventListener('click',e=>{const id=a.getAttribute('href').slice(1);if(!id)return;e.preventDefault();smoothTo(id)})});
const sections=[...document.querySelectorAll('main section[id], #home-section')],topLinks=[...document.querySelectorAll('.site-nav a')],sideLinks=[...document.querySelectorAll('.side-nav .side-item')],mapId=id=>id==='home-section'?'#home':`#${id}`;
if(sections.length){const io=new IntersectionObserver(es=>{es.forEach(en=>{if(!en.isIntersecting)return;const href=mapId(en.target.id||'home');topLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===href));sideLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===href))})},{threshold:.55});sections.forEach(s=>io.observe(s))}
;(function(){const el=document.getElementById('brand-gizmo');if(!el||prefersReduced)return;const c=document.createElement('canvas');c.width=c.height=22;el.appendChild(c);const x=c.getContext('2d');let px=11,py=11,vx=(Math.random()*2-1)*.6,vy=(Math.random()*2-1)*.6,t=0;function step(){x.clearRect(0,0,22,22);x.shadowColor='#30f179';x.shadowBlur=6;x.strokeStyle='#30f179';x.lineWidth=1;x.beginPath();for(let i=0;i<8;i++){const a=t*.06+i*(Math.PI/4),r=7+Math.sin(t*.08+i)*2,xx=11+Math.cos(a)*r,yy=11+Math.sin(a)*r;i?x.lineTo(xx,yy):x.moveTo(xx,yy)}x.closePath();x.globalAlpha=.65;x.stroke();x.globalAlpha=1;x.fillStyle='#30f179';x.beginPath();x.arc(px,py,1.6,0,Math.PI*2);x.fill();px+=vx;py+=vy;t++;if(px<3||px>19)vx*=-1;if(py<3||py>19)vy*=-1;if(Math.random()<.02){vx=(Math.random()*2-1)*.6;vy=(Math.random()*2-1)*.6}requestAnimationFrame(step)}requestAnimationFrame(step)})();
;(function(){const canvas=document.getElementById('geo-orb');if(!canvas||prefersReduced)return;const ctx=canvas.getContext('2d'),GREEN='#30f179';function ico(){const t=(1+Math.sqrt(5))/2;let v=[[-1,t,0],[1,t,0],[-1,-t,0],[1,-t,0],[0,-1,t],[0,1,t],[0,-1,-t],[0,1,-t],[t,0,-1],[t,0,1],[-t,0,-1],[-t,0,1]];v=v.map(p=>{const L=Math.hypot(...p);return[p[0]/L,p[1]/L,p[2]/L]});const f=[[0,11,5],[0,5,1],[0,1,7],[0,7,10],[0,10,11],[1,5,9],[5,11,4],[11,10,2],[10,7,6],[7,1,8],[3,9,4],[3,4,2],[3,2,6],[3,6,8],[3,8,9],[4,9,5],[2,4,11],[6,2,10],[8,6,7],[9,8,1]];return{verts:v,faces:f}}
function subdivide(verts,faces){const mid=new Map,key=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`,midpoint=(a,b)=>{const k=key(a,b);if(mid.has(k))return mid.get(k);const m=[(verts[a][0]+verts[b][0])/2,(verts[a][1]+verts[b][1])/2,(verts[a][2]+verts[b][2])/2],L=Math.hypot(...m),idx=verts.push([m[0]/L,m[1]/L,m[2]/L])-1;mid.set(k,idx);return idx};const nf=[];for(const [a,b,c]of faces){const ab=midpoint(a,b),bc=midpoint(b,c),ca=midpoint(c,a);nf.push([a,ab,ca],[b,bc,ab],[c,ca,bc],[ab,bc,ca])}return{verts,faces:nf}}
let {verts,faces}=ico();({verts,faces}=subdivide(verts,faces));const edgeSet=new Set();for(const [a,b,c]of faces)[[a,b],[b,c],[c,a]].forEach(([i,j])=>edgeSet.add(i<j?`${i}-${j}`:`${j}-${i}`));const edges=[...edgeSet].map(e=>e.split('-').map(Number));
function project([x,y,z],rx,ry,rz,R){let yy=y*Math.cos(rx)-z*Math.sin(rx),zz=y*Math.sin(rx)+z*Math.cos(rx),xx=x;const yy2=yy,zz2=zz*Math.cos(ry)-xx*Math.sin(ry),xx2=zz*Math.sin(ry)+xx*Math.cos(ry),x3=xx2*Math.cos(rz)-yy2*Math.sin(rz),y3=xx2*Math.sin(rz)+yy2*Math.cos(rz),d=2.8,s=(R*d)/(d+zz2);return[x3*s,y3*s]}
function fit(){const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width);canvas.height=Math.round(r.height)}fit();addEventListener('resize',fit,{passive:true});
const baseR=()=>Math.min(canvas.width,canvas.height)*.42;let rx=0,ry=0,rz=0,wx=.012,wy=.018,wz=.009,tx=wx,ty=wy,tz=wz,lerpT=1,nextChange=0,ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
function pick(){const mag=.006+Math.random()*.014;let ax=Math.random()*2-1,ay=Math.random()*2-1,az=Math.random()*2-1,L=Math.hypot(ax,ay,az)||1;ax/=L;ay/=L;az/=L;tx=ax*mag;ty=ay*mag;tz=az*mag;lerpT=0;nextChange=performance.now()+(3500+Math.random()*3000)}pick();
function draw(now){if(prefersReduced)return;if(lerpT<1){lerpT=Math.min(1,lerpT+.012);const k=ease(lerpT);wx+=(tx-wx)*k;wy+=(ty-wy)*k;wz+=(tz-wz)*k}if(now>=nextChange)pick();rx+=wx;ry+=wy;rz+=wz;ctx.clearRect(0,0,canvas.width,canvas.height);const cx=canvas.width/2,cy=canvas.height/2,R=baseR()*(1+.015*Math.sin(now*.0013)),pts=verts.map(v=>{const p=project(v,rx,ry,rz,R);return[p[0]+cx,p[1]+cy]});ctx.strokeStyle='#30f179';ctx.lineWidth=1.2;ctx.globalAlpha=.95;ctx.shadowColor='#30f179';ctx.shadowBlur=12;ctx.beginPath();for(const[i,j]of edges){const a=pts[i],b=pts[j];ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1])}ctx.stroke();requestAnimationFrame(draw)}requestAnimationFrame(draw)})();
;(async function(){const el=document.getElementById('views-count');if(!el)return;try{const r=await fetch('https://api.countapi.xyz/hit/brayan-portfolio/views');const d=await r.json();el.textContent=d&&typeof d.value==='number'?d.value.toLocaleString():'1'}catch{const k='local-views',v=parseInt(localStorage.getItem(k)||'0',10)+1;localStorage.setItem(k,String(v));el.textContent=v.toLocaleString()}})();
document.querySelectorAll('main section[id], #home-section').forEach(s=>s.setAttribute('tabindex','-1'));
;(function(){const root=document.querySelector('.project-tabs'),tabs=root?Array.from(root.querySelectorAll('.tab')):[],panel=document.getElementById('projects-panel'),cards=panel?Array.from(panel.querySelectorAll('.project-card')):[],sumPriceFull=document.getElementById('summary-price-full'),sumPriceMini=document.getElementById('summary-price-mini'),sumTime=document.getElementById('summary-time');if(!root||!tabs.length||!panel||!cards.length)return;const PRESETS={roblox:{full:'$80–$500 USD',mini:'$25–$80 USD',time:'1–3 days (small) · 7–30 days (full)'},web:{full:'$50–$250 USD',mini:'$50–$100 USD',time:'1–5 days (small) · 3–14 days (large)'}};function setSummary(k){const p=PRESETS[k];if(!p)return;sumPriceFull.textContent=p.full;sumPriceMini.textContent=p.mini;sumTime.textContent=p.time}
function pauseHidden(){cards.forEach(c=>{if(c.hasAttribute('hidden'))c.querySelectorAll('video').forEach(v=>{try{v.pause()}catch{}})})}
function activate(btn){tabs.forEach(t=>{const a=t===btn;t.classList.toggle('active',a);t.setAttribute('aria-selected',String(a));if(a&&panel)panel.setAttribute('aria-labelledby',t.id||'')});const k=btn.dataset.filter;cards.forEach(card=>{card.dataset.category===k?card.removeAttribute('hidden'):card.setAttribute('hidden','')});setSummary(k);pauseHidden()}
tabs.forEach(t=>t.addEventListener('click',()=>activate(t)));root.addEventListener('keydown',e=>{const i=tabs.indexOf(document.activeElement);if(i===-1)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const d=e.key==='ArrowRight'?1:-1,n=(i+d+tabs.length)%tabs.length;tabs[n].focus();activate(tabs[n])}if(e.key==='Home'){e.preventDefault();tabs[0].focus();activate(tabs[0])}if(e.key==='End'){e.preventDefault();tabs[tabs.length-1].focus();activate(tabs[tabs.length-1])}});
activate(tabs.find(t=>t.classList.contains('active'))||tabs[0])})();
